require "test_helper"

# Content-level test for InvoicePdf. The sibling invoice_pdf_test.rb is a magic-
# bytes smoke test; this one parses the rendered PDF back and asserts the actual
# strings InvoicePdf#draw is supposed to emit. Catches regressions where a label
# or format drifts but the PDF still renders.
class InvoicePdfContentTest < ActiveSupport::TestCase
  setup do
    @user     = users(:basic_user)
    @customer = setup_billing(@user)
    @charge   = make_charge(@customer, amount: 2900)
  end

  test "renders all the expected fields and labels" do
    text = extract_pdf_text(InvoicePdf.new(@charge).render)

    # Heading + status block
    assert_includes text, "Invoice"
    assert_includes text, "Invoice ##{@charge.id}"
    assert_includes text, "Issued: #{@charge.created_at.to_date}"
    assert_includes text, "Status: Paid"

    # From / Bill to columns
    assert_includes text, "From"
    assert_includes text, Pay.business_name
    assert_includes text, Pay.support_email.to_s
    assert_includes text, "Bill to"
    assert_includes text, @user.email

    # Table headers, row, and total
    assert_includes text, "Description"
    assert_includes text, "Amount"
    assert_includes text, "Charge" # no subscription -> falls back to "Charge"
    assert_includes text, "$29.00 USD"
    assert_includes text, "Total"

    # Footer
    assert_includes text, "Stripe charge: #{@charge.processor_id}"
    assert_includes text, "Generated by HexaPDF"
  end

  test "marks a refunded charge with the Refunded status" do
    @charge.update!(amount_refunded: 2900)
    text = extract_pdf_text(InvoicePdf.new(@charge).render)
    assert_includes text, "Status: Refunded"
  end

  test "uses the subscription plan and period in the line description when present" do
    subscription = Pay::Subscription.create!(
      customer:             @customer,
      name:                 "default",
      processor_id:         "sub_content_test",
      processor_plan:       "price_pro_monthly",
      status:               "active",
      current_period_start: Date.new(2026, 1, 1),
      current_period_end:   Date.new(2026, 2, 1)
    )
    @charge.update!(subscription: subscription)

    text = extract_pdf_text(InvoicePdf.new(@charge).render)

    assert_includes text, "price_pro_monthly"
    assert_includes text, "2026-01-01"
    assert_includes text, "2026-02-01"
  end
end
