require "test_helper"

# Direct tests for the Pdf base class primitives. Each test defines a tiny
# StubPdf subclass that exercises one primitive, renders the PDF, parses it
# back with HexaPDF (via the PdfTextExtraction helper), and asserts the
# extracted text. No HTTP, no Stripe.
class PdfTest < ActiveSupport::TestCase
  def render_and_extract(&draw_block)
    klass = Class.new(Pdf) { define_method(:draw, &draw_block) }
    bytes = klass.new.render
    [ bytes, extract_pdf_text(bytes) ]
  end

  # ---- low-level primitives ------------------------------------------------

  test "text draws a string at the given coordinates" do
    _bytes, text = render_and_extract { text("hello world", at: [ 100, 700 ]) }
    assert_includes text, "hello world"
  end

  test "rule draws a horizontal line without raising" do
    bytes, _text = render_and_extract { rule(500) }
    assert bytes.start_with?("%PDF"), "rule should still produce a valid PDF"
  end

  test "money formats cents to dollars with currency suffix" do
    _bytes, text = render_and_extract { text(money(1234, "usd"), at: [ 100, 700 ]) }
    assert_includes text, "$12.34 USD"
  end

  test "money upcases the currency code" do
    _bytes, text = render_and_extract { text(money(50, :eur), at: [ 100, 700 ]) }
    assert_includes text, "$0.50 EUR"
  end

  # ---- mid-level primitives ------------------------------------------------

  test "heading draws the title text" do
    _bytes, text = render_and_extract { heading("Invoice") }
    assert_includes text, "Invoice"
  end

  test "meta_lines stacks every provided line" do
    _bytes, text = render_and_extract do
      meta_lines([ "Invoice #1", "Issued: 2026-01-01", "Status: Paid" ])
    end
    assert_includes text, "Invoice #1"
    assert_includes text, "Issued: 2026-01-01"
    assert_includes text, "Status: Paid"
  end

  test "two_columns renders both column blocks" do
    _bytes, text = render_and_extract do
      two_columns(
        left:  [ "From", "Acme Inc.", "support@acme.test" ],
        right: [ "Bill to", "customer@example.test" ]
      )
    end
    assert_includes text, "From"
    assert_includes text, "Acme Inc."
    assert_includes text, "support@acme.test"
    assert_includes text, "Bill to"
    assert_includes text, "customer@example.test"
  end

  test "table renders headers and every row" do
    _bytes, text = render_and_extract do
      table(
        columns: [ { label: "Description", x: 50 }, { label: "Amount", x: 450 } ],
        rows:    [ [ "Pro plan", "$29.00 USD" ], [ "Add-on", "$5.00 USD" ] ],
        top_y:   640
      )
    end
    assert_includes text, "Description"
    assert_includes text, "Amount"
    assert_includes text, "Pro plan"
    assert_includes text, "$29.00 USD"
    assert_includes text, "Add-on"
    assert_includes text, "$5.00 USD"
  end

  test "total_row writes label and value" do
    _bytes, text = render_and_extract do
      total_row(label: "Total", value: "$29.00 USD", y: 565)
    end
    assert_includes text, "Total"
    assert_includes text, "$29.00 USD"
  end

  test "footer_lines stacks every footer line" do
    _bytes, text = render_and_extract do
      footer_lines([ "Stripe charge: ch_test", "Generated by HexaPDF." ])
    end
    assert_includes text, "Stripe charge: ch_test"
    assert_includes text, "Generated by HexaPDF."
  end

  # ---- structural ----------------------------------------------------------

  test "render returns a non-empty PDF binary" do
    bytes, _text = render_and_extract { heading("ok") }
    assert_kind_of String, bytes
    assert bytes.bytesize.positive?
    assert bytes.start_with?("%PDF"), "expected PDF magic header"
  end

  test "filename defaults to underscored class name without _pdf suffix" do
    receipt_class = Class.new(Pdf) do
      def self.name
        "ReceiptPdf"
      end

      def draw; end
    end
    assert_equal "receipt.pdf", receipt_class.new.filename
  end

  test "draw raises NotImplementedError when subclass forgets to define it" do
    bare = Class.new(Pdf) do
      def self.name
        "BarePdf"
      end
    end
    assert_raises(NotImplementedError) { bare.new.render }
  end
end
