class InvoicePdf < Pdf
  COLUMNS = [
    { label: "Description", x: CONTENT_LEFT },
    { label: "Amount",      x: 450 }
  ].freeze

  def initialize(charge)
    @charge = charge
  end

  def filename
    "invoice-#{charge.created_at.to_date.strftime('%Y%m%d')}-##{charge.id}.pdf"
  end

  protected

  def draw
    heading "Invoice"
    meta_lines [ "Invoice ##{charge.id}", "Issued: #{charge.created_at.to_date}", "Status: #{status_text}" ]

    two_columns(
      left:  [ "From",    Pay.business_name, Pay.support_email ],
      right: [ "Bill to", charge.customer.owner.email ]
    )

    table(columns: COLUMNS, rows: [ [ line_description, formatted_amount ] ], top_y: 640)
    total_row(label: "Total", value: formatted_amount, y: 565)

    footer_lines [
      "Stripe charge: #{charge.processor_id}",
      "Generated by HexaPDF for the Stripe PDF Generation Demo."
    ]
  end

  private

  attr_reader :charge

  def status_text
    charge.amount_refunded.to_i.positive? ? "Refunded" : "Paid"
  end

  def line_description
    sub = charge.subscription
    return "Charge" unless sub

    period = [ sub.current_period_start&.to_date, sub.current_period_end&.to_date ].compact.join(" – ")
    label  = sub.processor_plan.presence || "Subscription"
    period.present? ? "#{label} (#{period})" : label
  end

  def formatted_amount
    money(charge.amount, charge.currency)
  end
end
