default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  # username: postgres
  # password: <%= ENV["STRIPE_PDF_GENERATION_DEMO_DATABASE_PASSWORD"] %>
  # host: 127.0.0.1

development:
  <<: *default
  database: stripe_pdf_generation_demo_development

test:
  <<: *default
  database: stripe_pdf_generation_demo_test

production:
  primary: &primary_production
    <<: *default
    database: stripe_pdf_generation_demo_production
    username: stripe_pdf_generation_demo
    password: <%= ENV["STRIPE_PDF_GENERATION_DEMO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: stripe_pdf_generation_demo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: stripe_pdf_generation_demo_production_queue
    migrations_paths: db/queue_migrate
