require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: ENV.fetch("PORT", 3200).to_i }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # The four flags below add useful debugging context but each one costs a
  # bit of CPU and a lot of log spam. Flip back to true while debugging a
  # specific issue; otherwise leave off for snappier dev.
  config.active_record.verbose_query_logs       = false
  config.active_record.query_log_tags_enabled   = false
  config.active_job.verbose_enqueue_logs        = false
  config.action_dispatch.verbose_redirect_logs  = false

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotating templates with <!-- BEGIN app/views/... --> comments is nice
  # for spelunking, slow when chained partials render dozens of times. Off
  # by default; toggle on when you need to find where markup is coming from.
  config.action_view.annotate_rendered_view_with_filenames = false

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  config.action_mailer.default_url_options = { host: "localhost", port: ENV.fetch("PORT", 3200).to_i }

  config.hosts << /.*\.taile00403\.ts\.net/

  # web-console is dev-only (loaded from the :development group), so there is
  # no production risk in opening it to any IP. Default permissions are just
  # 127.0.0.1 / ::1, which silently drops the inline exception console on any
  # request coming through a tunnel, LAN device, or container. Open it up.
  config.web_console.permissions = [ "0.0.0.0/0", "::/0" ] if defined?(WebConsole)

  config.after_initialize do
    # Bullet stays on so we catch N+1s and unused eager-loads, but quietly:
    # just rails_logger. The other channels (bullet.log file, JS console
    # alerts, on-page footer) add up to noticeable per-request overhead and
    # make the page feel sluggish in dev.
    Bullet.enable        = true
    Bullet.rails_logger  = true
    Bullet.bullet_logger = false
    Bullet.console       = false
    Bullet.add_footer    = false
  end
end
